# Output (managed by kanshi for multi-monitor)
output * bg ~/.local/share/backgrounds/2024-04-02-16-39-10-linux_wallpapers.jpg fill

# Touchpad
input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}

# Keyboard
input type:keyboard {
    xkb_layout es
    xkb_options caps:swapescape
}
