# Modifier
set $mod Mod4

# Vim direction keys
set $left h
set $down j
set $up k
set $right l

# Applications
set $term kitty
set $menu fuzzel
set $lockscreen swaylock -f -c 1a1a2e

# Screenshots
set $screenshot bash -c 'grim - | wl-copy'
set $screenshot_clip bash -c 'grim -g "$(slurp)" - | wl-copy'
set $screenshot_edit bash -c 'grim -g "$(slurp)" - | swappy -f -'
