# Borders
default_border normal 1
default_floating_border pixel 1

# Gaps
gaps inner 4
gaps outer 0

# Font
font pango:JetBrains Mono 10

# Colors (Catppuccin Mocha)
#                       border  bground text    indicator child_border
client.focused          #cba6f7 #cba6f7 #1e1e2e #f5c2e7   #cba6f7
client.focused_inactive #45475a #45475a #bac2de #45475a    #45475a
client.unfocused        #313244 #313244 #a6adc8 #313244    #313244
client.urgent           #f38ba8 #f38ba8 #1e1e2e #fab387    #f38ba8

# Tab accent
for_window [app_id=".*"] title_format <span foreground="#cba6f7">▎</span> %title
for_window [class=".*"] title_format <span foreground="#cba6f7">▎</span> %title

